### ISSUE TITLE
demosite not registering client in Gluu OP

### ISSUE THREAD

**Issue by abel408** [GluuFederation/oxd-python#7] opened 2017-04-14 15:58 UTC
I'm trying to work with the demosite and Gluu OP 3.0.1. I have a brand new install of both. When I click the "Go to Authorization Page" button, I get the following from Gluu OP:

> {"error":"unauthorized_client","error_description":"The client is not authorized to request an access token using this method.","state":"ggp0q4nv83p8lbirl4uvjmoe4e"}

I did see an entry get added to /opt/oxd-server/conf, but not to the Gluu OP in OpenID Connect -> Clients.

I tried removing the entry from /opt/oxd-server/conf in an attempt to reregister the client. That did not work. So now I do not have an entry in /opt/oxd-server/conf or on the Gluu OP.

I'm wondering if this demosite ever got tested with Gluu 3.0.1.

**Comment by tecoholic** [comment] 2017-04-14 16:12
@abel408 Yes, it was tested with Gluu 3.0.1. If you want to try again, open your demosite.cfg file and empty the value of id and reregister the client.

**Comment by tecoholic** [comment] 2017-04-14 16:18
Also it is a little weird that you got the the json file created in the /opt/oxd-server/conf and couldn't find an entry in the Gluu Server. Kindly check the values of `op_host` you are using. There are two places to put it, `/opt/oxd-server/conf/oxd-default-site-config.json` and in the `demosite.cfg` file. If you have a `op_host` value configured the default site configuration, there is no need to use it in the demosite.cfg. Your error could be caused, when you are using two different values in these two places. Kindly ensure that's not the case. 

Meanwhile, we will try to reproduce the error on our side and update the ticket.

**Comment by abel408** [comment] 2017-04-14 16:49
The demosite.cfg file does not have anything after "id =". I did have my op_host in both demosite.cfg and oxd-default-site-config.json. I removed it from demosite.cfg.

After not seeing any changed, I restarted the oxd service. I am now getting an internal error and the oxd-server log shows this:

> 2017-04-14 12:43:02,717 TRACE [org.xdi.oxd.common.CoreUtils] Read result: ReadResult{m_command='{"params": {"oxd_id": "e1cdeba0-d23b-4b6d-8156-268da41b9e48"}, "command": "get_authorization_url"}', m_leftString=''}
2017-04-14 12:43:02,717 TRACE [org.xdi.oxd.server.Processor] Command: {"params": {"oxd_id": "e1cdeba0-d23b-4b6d-8156-268da41b9e48"}, "command": "get_authorization_url"}
2017-04-14 12:43:02,766 ERROR [org.xdi.oxd.server.Processor] 
ErrorResponseException{errorResponseCode=ErrorResponseCode{value='invalid_oxd_id', description='Invalid oxd_id. Unable to find site for oxd_id. Please use register_site command for site registration.'}}


That id was the old id that I had removed already. Not sure where it is getting it from.

**Comment by abel408** [comment] 2017-04-14 19:50
We can probably remove this... This looks like an issue with my gluu server or web server. The demo-cgi app that I had working is no longer working now either. The client some how removed itself from my gluu server.

**Comment by nynymike** [comment] 2017-04-18 16:42
Dynamically registered clients automatically expire in one day, unless extended by the OP admin. I'm closing this issue because this is not the right place to get support. Please register on https://support.gluu.org

**Closed by nynymike** 2017-04-18 16:42 UTC
